// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: rtcenter/data.proto

package rtcenter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StringMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *StringMsg) Reset() {
	*x = StringMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtcenter_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMsg) ProtoMessage() {}

func (x *StringMsg) ProtoReflect() protoreflect.Message {
	mi := &file_rtcenter_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMsg.ProtoReflect.Descriptor instead.
func (*StringMsg) Descriptor() ([]byte, []int) {
	return file_rtcenter_data_proto_rawDescGZIP(), []int{0}
}

func (x *StringMsg) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Int32Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data int32 `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Int32Msg) Reset() {
	*x = Int32Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtcenter_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int32Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32Msg) ProtoMessage() {}

func (x *Int32Msg) ProtoReflect() protoreflect.Message {
	mi := &file_rtcenter_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32Msg.ProtoReflect.Descriptor instead.
func (*Int32Msg) Descriptor() ([]byte, []int) {
	return file_rtcenter_data_proto_rawDescGZIP(), []int{1}
}

func (x *Int32Msg) GetData() int32 {
	if x != nil {
		return x.Data
	}
	return 0
}

type Int64Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data int64 `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Int64Msg) Reset() {
	*x = Int64Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtcenter_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int64Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64Msg) ProtoMessage() {}

func (x *Int64Msg) ProtoReflect() protoreflect.Message {
	mi := &file_rtcenter_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64Msg.ProtoReflect.Descriptor instead.
func (*Int64Msg) Descriptor() ([]byte, []int) {
	return file_rtcenter_data_proto_rawDescGZIP(), []int{2}
}

func (x *Int64Msg) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

type DoubleMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data float64 `protobuf:"fixed64,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DoubleMsg) Reset() {
	*x = DoubleMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtcenter_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoubleMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleMsg) ProtoMessage() {}

func (x *DoubleMsg) ProtoReflect() protoreflect.Message {
	mi := &file_rtcenter_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleMsg.ProtoReflect.Descriptor instead.
func (*DoubleMsg) Descriptor() ([]byte, []int) {
	return file_rtcenter_data_proto_rawDescGZIP(), []int{3}
}

func (x *DoubleMsg) GetData() float64 {
	if x != nil {
		return x.Data
	}
	return 0
}

//
//以订阅快照为例:
//msgType:snapshot        string
//symbol:600000.SH        repeated string
//fields: [open,close]    repeated string
type VDSReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqMap map[string]string `protobuf:"bytes,1,rep,name=req_map,json=reqMap,proto3" json:"req_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *VDSReq) Reset() {
	*x = VDSReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtcenter_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VDSReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VDSReq) ProtoMessage() {}

func (x *VDSReq) ProtoReflect() protoreflect.Message {
	mi := &file_rtcenter_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VDSReq.ProtoReflect.Descriptor instead.
func (*VDSReq) Descriptor() ([]byte, []int) {
	return file_rtcenter_data_proto_rawDescGZIP(), []int{4}
}

func (x *VDSReq) GetReqMap() map[string]string {
	if x != nil {
		return x.ReqMap
	}
	return nil
}

type MapValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *anypb.Any `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MapValue) Reset() {
	*x = MapValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtcenter_data_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapValue) ProtoMessage() {}

func (x *MapValue) ProtoReflect() protoreflect.Message {
	mi := &file_rtcenter_data_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapValue.ProtoReflect.Descriptor instead.
func (*MapValue) Descriptor() ([]byte, []int) {
	return file_rtcenter_data_proto_rawDescGZIP(), []int{5}
}

func (x *MapValue) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type VDSRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RspMap map[string]*MapValue `protobuf:"bytes,1,rep,name=rsp_map,json=rspMap,proto3" json:"rsp_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *VDSRsp) Reset() {
	*x = VDSRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtcenter_data_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VDSRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VDSRsp) ProtoMessage() {}

func (x *VDSRsp) ProtoReflect() protoreflect.Message {
	mi := &file_rtcenter_data_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VDSRsp.ProtoReflect.Descriptor instead.
func (*VDSRsp) Descriptor() ([]byte, []int) {
	return file_rtcenter_data_proto_rawDescGZIP(), []int{6}
}

func (x *VDSRsp) GetRspMap() map[string]*MapValue {
	if x != nil {
		return x.RspMap
	}
	return nil
}

var File_rtcenter_data_proto protoreflect.FileDescriptor

var file_rtcenter_data_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x74, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x76, 0x64, 0x73, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x19,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1f, 0x0a, 0x09, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1e, 0x0a, 0x08, 0x49, 0x6e,
	0x74, 0x33, 0x32, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1e, 0x0a, 0x08, 0x49, 0x6e,
	0x74, 0x36, 0x34, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1f, 0x0a, 0x09, 0x44, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x79, 0x0a, 0x06, 0x56,
	0x44, 0x53, 0x52, 0x65, 0x71, 0x12, 0x34, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x5f, 0x6d, 0x61, 0x70,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x76, 0x64, 0x73, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x56, 0x44, 0x53, 0x52, 0x65, 0x71, 0x2e, 0x52, 0x65, 0x71, 0x4d, 0x61, 0x70, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x06, 0x72, 0x65, 0x71, 0x4d, 0x61, 0x70, 0x1a, 0x39, 0x0a, 0x0b, 0x52,
	0x65, 0x71, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x36, 0x0a, 0x08, 0x4d, 0x61, 0x70, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x8c,
	0x01, 0x0a, 0x06, 0x56, 0x44, 0x53, 0x52, 0x73, 0x70, 0x12, 0x34, 0x0a, 0x07, 0x72, 0x73, 0x70,
	0x5f, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x76, 0x64, 0x73,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x56, 0x44, 0x53, 0x52, 0x73, 0x70, 0x2e, 0x52, 0x73, 0x70, 0x4d,
	0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x72, 0x73, 0x70, 0x4d, 0x61, 0x70, 0x1a,
	0x4c, 0x0a, 0x0b, 0x52, 0x73, 0x70, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x27, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x76, 0x64, 0x73, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4d, 0x61, 0x70, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x0c, 0x5a,
	0x0a, 0x2e, 0x2f, 0x72, 0x74, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_rtcenter_data_proto_rawDescOnce sync.Once
	file_rtcenter_data_proto_rawDescData = file_rtcenter_data_proto_rawDesc
)

func file_rtcenter_data_proto_rawDescGZIP() []byte {
	file_rtcenter_data_proto_rawDescOnce.Do(func() {
		file_rtcenter_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_rtcenter_data_proto_rawDescData)
	})
	return file_rtcenter_data_proto_rawDescData
}

var file_rtcenter_data_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rtcenter_data_proto_goTypes = []interface{}{
	(*StringMsg)(nil), // 0: vdsdata.StringMsg
	(*Int32Msg)(nil),  // 1: vdsdata.Int32Msg
	(*Int64Msg)(nil),  // 2: vdsdata.Int64Msg
	(*DoubleMsg)(nil), // 3: vdsdata.DoubleMsg
	(*VDSReq)(nil),    // 4: vdsdata.VDSReq
	(*MapValue)(nil),  // 5: vdsdata.MapValue
	(*VDSRsp)(nil),    // 6: vdsdata.VDSRsp
	nil,               // 7: vdsdata.VDSReq.ReqMapEntry
	nil,               // 8: vdsdata.VDSRsp.RspMapEntry
	(*anypb.Any)(nil), // 9: google.protobuf.Any
}
var file_rtcenter_data_proto_depIdxs = []int32{
	7, // 0: vdsdata.VDSReq.req_map:type_name -> vdsdata.VDSReq.ReqMapEntry
	9, // 1: vdsdata.MapValue.value:type_name -> google.protobuf.Any
	8, // 2: vdsdata.VDSRsp.rsp_map:type_name -> vdsdata.VDSRsp.RspMapEntry
	5, // 3: vdsdata.VDSRsp.RspMapEntry.value:type_name -> vdsdata.MapValue
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rtcenter_data_proto_init() }
func file_rtcenter_data_proto_init() {
	if File_rtcenter_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rtcenter_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtcenter_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int32Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtcenter_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int64Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtcenter_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoubleMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtcenter_data_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VDSReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtcenter_data_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtcenter_data_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VDSRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rtcenter_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rtcenter_data_proto_goTypes,
		DependencyIndexes: file_rtcenter_data_proto_depIdxs,
		MessageInfos:      file_rtcenter_data_proto_msgTypes,
	}.Build()
	File_rtcenter_data_proto = out.File
	file_rtcenter_data_proto_rawDesc = nil
	file_rtcenter_data_proto_goTypes = nil
	file_rtcenter_data_proto_depIdxs = nil
}
